"""Add soft delete fields and is_active

Revision ID: 5b9fe6bb3aca
Revises: 99609661bc2f
Create Date: 2025-10-27 11:03:22.284372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9fe6bb3aca'
down_revision = '99609661bc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('articles', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('comments', 'deleted_at')
    op.drop_column('comments', 'is_deleted')
    op.alter_column('articles', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'is_deleted')
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###