"""Add soft delete fields

Revision ID: 6227fe8873d2
Revises: 5b9fe6bb3aca
Create Date: 2025-10-27 11:11:47.134522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6227fe8873d2'
down_revision = '5b9fe6bb3aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###