"""Initial Docker setup

Revision ID: 99609661bc2f
Revises: 
Create Date: 2025-10-26 00:49:10.359798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99609661bc2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###